create table hmds (
	id INTEGER primary key generated by default as identity,
	name text not null,
	image text not null,
	video text not null,
	page text,
	panel text,
	resolution text not null ,
	ppd text,
	refrate text not null,
	fov text not null,
	tracking text not null,
	price text not null,
	rating INTEGER not null default 0
	);